import Head from "next/head";
import styles from "./index.module.scss"
import cn from "classnames";
import { NextPage } from "next";
import { useState } from "react";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const [isEnableText3, setIsEnablText3] = useState(false);
  console.log(isEnableText3);

  const router = useRouter();

  const sum = (num1: number, num2: number) => {
    return num1 + num2;
  };

  const sum2 = (num1: number, num2: number) => num1 + num2;
  console.log(sum(2,3));
  console.log(sum(5,6));

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        ログインページです
        <button onClick={() => router.push("../")}>
          TOPページへ
        </button>
      </div>
    </>
  );
}
export default Home