import Head from "next/head";
import styles from "./index.module.scss";
import cn from "classnames";
import { CheckBox } from "@/components/atoms/CheckBox";
import { NextPage } from "next";
import { useState } from "react";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const router = useRouter();

  // let isEnableText3 = false;, 
  const [isEnableText3, setIsEnableText3] = useState(false);
  
  const [isEnableText4, setIsEnableText4] = useState(true);

  const sum = (num1: number, num2: number) => {
    return num1 + num2;
  };

  const sum2 = (num1: number, num2: number) => num1 + num2;

  console.log(sum(5, 6));

  console.log(sum2(2, 3));

  const students = [
    { id: 1, name: "一郎", age: 16 },
    { id: 2, name: "二郎", age: 15 },
    { id: 3, name: "三郎", age: 14 },
  ];

  const nameList = students.map((elem) => elem.name)
  const ageList = students.map((elem) => elem.age);

  const ageList2 = students.map((elem, index) => {
    return elem.age;
  });

  console.log(ageList,nameList);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <CheckBox labelName="test"/>
        こんにちは
        <div className={styles.container__text1}>test</div>
        <div
        // 動的なクラスであるisEnableTextの管理
          className={cn(styles.container__text1, styles.container__text2, {
            [styles.container__text3]: isEnableText3,
            [styles.container__text4]: isEnableText4,
          })}
        >
          test2
        </div>
        {/* setIsEnableText3を呼び出し、isEnableText3の現在の値を反転させ新しい状態として設定する */}
        <button onClick={() => setIsEnableText3(!isEnableText3)}>
          テキスト３有効化ボタン
        </button>
        <button onClick={() => setIsEnableText4(!isEnableText4)}>
          テキスト４無効化ボタン
        </button>
        <button onClick={() => router.push("/login")}>ログインページへ</button>
        <button onClick={() => router.push("/test")}>テストページへ</button>
        <button onClick={() => router.push("/suumo")}>Suumoページへ</button>
        {students.map((elem) => (
          <div key={elem.id}>
            <div>名前：{elem.name}</div>
            <div>年齢：{elem.age}</div>
          </div>
        ))}
        <div>
          {sum(1,5)}
        </div>
      </div>
    </>
  );
};
export default Home;
