import Head from "next/head";
import styles from "./index.module.scss";
import cn from "classnames";
import { NextPage } from "next";
import { useState } from "react";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const router = useRouter();

  const [isEnableText3, setIsEnableText3] = useState(false);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        こんにちは
        <div className={styles.container__text1}>test</div>
        <div
          // 動的なクラスであるisEnableTextの管理
          className={cn(styles.container__text1, styles.container__text2, {
            [styles.container__text3]: isEnableText3,
          })}
        >
          test2
        </div>
        {/* setIsEnableText3を呼び出し、isEnableText3の現在の値を反転させ新しい状態として設定する */}
        <button onClick={() => setIsEnableText3(!isEnableText3)}>
          テキスト３有効化ボタン
        </button>
        {/* <button onClick={() => router.push("/test")}>テストページへ</button> */}
        {/* <button onClick={() => router.push("/test2")}>テストページ2へ</button> */}
        <button onClick={() => router.push("/test3")}>テストページ3へ</button>
        <button onClick={() => router.push("/test4")}>テストページ4へ</button>
        <button onClick={() => router.push("/test7")}>テストページ7へ</button>
        <button onClick={() => router.push("/test8")}>テストページ8へ</button>
        <button onClick={() => router.push("/suumo")}>Suumoページへ</button>
      </div>
    </>
  );
};
export default Home;
