import Head from "next/head";
import styles from "./index.module.scss";
//  デフォルトエクスポートだから名前指定はなんでもいい
import cn from "classnames";
import { NextPage } from "next";
import { useState } from "react";
import { useRouter } from "next/router";

// 関数コンポーネント、アッパーキャメルケース
const Home: NextPage = () => {
  const router = useRouter();

  const greeting = (userName: string) => `Hello, ${userName}!`;

  console.log(greeting("tarou"));

  const greeting2 = (userName2: string, greetingType: String) => {
    let greet: string;
    if (greetingType === "morning") {
      greet = "おはよう";
    } else if (greetingType === "night") {
      greet = "こんばんは";
    } else {
      greet = "こんにちは";
    }
    return `${userName2}, ${greet}`;
  };

  console.log(greeting2("二郎", "morning"));

  const students: {
    id: number;
    name: string;
    age: number;
    prefecture: string;
    jobHunt: boolean;
  }[] = [
    { id: 1, name: "太郎", age: 28, prefecture: "石川県", jobHunt: false },
    { id: 2, name: "花子", age: 26, prefecture: "大阪府", jobHunt: true },
    { id: 3, name: "二郎", age: 25, prefecture: "北海道", jobHunt: false },
  ];

  const introductions = students.map((student) => {
    return `はじめまして。${student.name}と申します。${
      student.prefecture
    }出身で、今年で${student.age}歳になります。就職先は${
      student.jobHunt ? "決まりました" : "まだ決まっていません"
    }。`;
  });

  introductions.forEach((intro) => {
    console.log(intro);
  });

  const teachers:{
    id:number, teacherName:string, age:number
  } []= [
    {id:1, teacherName:"佐藤", age:40},
    {id:2, teacherName:"高橋", age:37},
    {id:3, teacherName:"井上", age:30},
  ]

  const teacherNameList = teachers.map((tname)=>{
    return tname.teacherName
  });

  console.log(teacherNameList);
  

  const [changeBackGround, setChangeBackGround] = useState(false);

  const[changeColor, setChangeColor] = useState(false);

  return (
    // reactフラグメント省略形式
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* classは予約語なので使えない,最上位に１つの要素が必要なのでdiv */}
      <div
        className={cn(styles.container, {
          [styles.container__background]: changeBackGround,
        })}
      >
        <h1 className={styles.container__test}>テスト用</h1>
        <button
          onClick={() => router.push("../")}
          className={styles.container__button}
        >
          TOPページに戻ります
        </button>

        <button onClick={() => setChangeBackGround(!changeBackGround)}>
          背景色変更ボタン
        </button>

        <button onClick={()=> setChangeColor(!changeColor)}>文字色変更ボタン</button>

        {students.map((student) => (
          <p className={cn({
            [styles.container__textColor]: changeColor
          })}>
            はじめまして。{student.name}と申します。{student.age}歳です。
            {student.prefecture}出身です。就職活動は
            {student.jobHunt ? "終わりました" : "まだ続けています"}。
          </p>
        ))}
      </div>
    </>
  );
};
export default Home;
