import Head from "next/head";
import styles from "./index.module.scss";
//  デフォルトエクスポートだから名前指定はなんでもいい
import cn from "classnames";
import { NextPage } from "next";
import { useState } from "react";
import { useRouter } from "next/router";

// 関数コンポーネント、アッパーキャメルケース
const Home: NextPage = () => {
  const router = useRouter();

  const [changeBackGround, setChangeBackGround] = useState(false);

  const [changeColor, setChangeColor] = useState(false);

  const [changeFontSize, setChangeFontSize] = useState(false);

  type Student = {
    id: number;
    name: string;
    prefecture: string;
    age: number;
    height: number;
  };

  const students: Student[] = [
    { id: 1, name: "太郎", prefecture: "愛知県", age: 27, height: 160 },
    { id: 2, name: "花子", prefecture: "京都府", age: 28, height: 155 },
    { id: 3, name: "二郎", prefecture: "広島県", age: 24, height: 165 },
    { id: 4, name: "三郎", prefecture: "福井県", age: 22, height: 170 },
  ];

  const users = [
    { name: "John", age: 30 },
    { name: "Jane", age: 25 },
    { name: "Jack", age: 35 }
];

// 例: `extractProperty(users, "name")` -> ["John", "Jane", "Jack"]

const extractProperty = users.map((user) => user.name)
  console.log(extractProperty)

  const numbers = [10, 5, 20, 3, 7];

// 例: [10, 5, 20, 3, 7] -> 3

console.log(Math.min(...numbers))
   

  const [count, setCount] = useState(0);

  const plusClick = () => setCount(count + 1);

  const minusClick = () => setCount(count - 1);
  return (
    // reactフラグメント省略形式
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* classは予約語なので使えない */}
      <div
        className={cn(styles.container, {
          [styles.container__background]: changeBackGround,
        })}
      >
        <div
          className={cn({
            [styles.sample__text]: changeFontSize,
          })}
        >
          sample text
        </div>
        <div className=""></div>
        <h1 className={styles.container__test}>テスト用</h1>
        <button
          onClick={() => router.push("../")}
          className={styles.container__button}
        >
          TOPページに戻ります
        </button>

        <button onClick={() => setChangeBackGround(!changeBackGround)}>
          背景色変更ボタン
        </button>

        <button onClick={() => setChangeColor(!changeColor)}>
          文字色変更ボタン
        </button>

        <button onClick={() => setChangeFontSize(!changeFontSize)}>
          文字サイズ変更ボタン
        </button>

        <div>{count}</div>
        <button onClick={plusClick}>+</button>
        <button onClick={minusClick}>-</button>

        {students.map(({ id, name, prefecture, age, height }) => (
          <div key={id}>
            <p>
              こんにちは！{name}と申します。{prefecture}出身で、
              {age}歳です。身長は{height}
              cmです。よろしくお願いします！
            </p>
          </div>
        ))}
      </div>
    </>
  );
};
export default Home;
